### ISSUE TITLE
rendering

### ISSUE THREAD

**Issue by nembal** [decentralized-identity/decentralized-identity.github.io#167]
[13:26:40] Using gulpfile ~/Documents/GitHub/decentralized-identity.github.io/gulpfile.js
[13:26:40] Starting 'watch'...
[13:26:42] Starting 'build'...
[13:26:42] Starting 'assets'...
[13:26:42] Starting 'templates'...
[13:26:42] Finished 'templates' after 22 ms
[13:26:44] The following tasks did not complete: watch, build, assets
[13:26:44] Did you forget to signal async completion?

events.js:292
      throw er; // Unhandled 'error' event
      ^
Template render error: (unknown path) [Line 167, Column 5]
  unexpected token: }
    at Object._prettifyError (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/nunjucks/src/environment.js:536:21)
    at Environment.renderString (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/nunjucks/src/environment.js:378:17)
    at DestroyableTransform._transform (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/gulp-nunjucks-render/index.js:59:15)
    at DestroyableTransform.Transform._read (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
Emitted 'error' event on Domain instance at:
    at DestroyableTransform.EventEmitter.emit (domain.js:517:12)
    at DestroyableTransform.onerror (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:315:20)
    at DestroyableTransform.EventEmitter.emit (domain.js:467:12)
    at /Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/gulp-nunjucks-render/index.js:61:17
    at /Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/nunjucks/src/environment.js:39:5
    at RawTask.call (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/asap/asap.js:40:19)
    at flush (/Users/nembal/Documents/GitHub/decentralized-identity.github.io/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-nunjucks',
  showProperties: true,
  showStack: false,
  fileName: '/Users/nembal/Documents/GitHub/decentralized-identity.github.io/templates/pages/governance/about.html',
  domainEmitter: DestroyableTransform {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: Pumpify {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: WriteStream {
            _writableState: [WritableState],
            writable: true,
            _events: [Object: null prototype],
            _eventsCount: 5,
            _maxListeners: undefined,
            _worker: [Function: sinker],
            _flush: null,
            [Symbol(kCapture)]: false
          },
          pipesCount: 1,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null
        },
        readable: true,
        _events: [Object: null prototype] {
          end: [ [Function], [Function] ],
          close: [ [Function: onclose], [Function] ],
          prefinish: [Function (anonymous)],
          newListener: [Function: removeSink],
          removeListener: [ [Function: removeSink], [Function: addSink] ],
          unpipe: [Function: onunpipe],
          drain: [Function (anonymous)],
          error: [Function: onerror],
          finish: [Function: bound onceWrapper] {
            listener: [Function: onfinish]
          },
          data: [Function: ondata]
        },
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function (anonymous)],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: CorkedRequest {
            next: null,
            entry: null,
            finish: [Function (anonymous)]
          }
        },
        writable: true,
        allowHalfOpen: true,
        _writable: DestroyableTransform {
          _readableState: ReadableState {
            objectMode: true,
            highWaterMark: 16,
            buffer: [BufferList],
            length: 0,
            pipes: [DestroyableTransform],
            pipesCount: 1,
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: false,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: true,
          _events: [Object: null prototype] {
            end: [Array],
            prefinish: [Function: prefinish],
            close: [Array],
            finish: [Array],
            error: [Array],
            data: [Function: ondata],
            drain: [Function: ondrain]
          },
          _eventsCount: 7,
          _maxListeners: undefined,
          _writableState: WritableState {
            objectMode: true,
            highWaterMark: 16,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function (anonymous)],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [CorkedRequest]
          },
          writable: true,
          allowHalfOpen: true,
          _transformState: {
            afterTransform: [Function: bound afterTransform],
            needTransform: true,
            transforming: false,
            writecb: null,
            writechunk: null,
            writeencoding: 'utf8'
          },
          _destroyed: false,
          _transform: [Function: normalize],
          [Symbol(kCapture)]: false
        },
        _readable: DestroyableTransform {
          _readableState: ReadableState {
            objectMode: true,
            highWaterMark: 16,
            buffer: [BufferList],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: null,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: true,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: true,
          _events: [Object: null prototype] {
            end: [Array],
            prefinish: [Function: prefinish],
            close: [Array],
            finish: [Array],
            error: [Array],
            unpipe: [Function: onunpipe],
            drain: [Function (anonymous)],
            readable: [Function: onreadable]
          },
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: WritableState {
            objectMode: true,
            highWaterMark: 16,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 1,
            writing: true,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function (anonymous)],
            writecb: [Function: nop],
            writelen: 1,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 1,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [CorkedRequest]
          },
          writable: true,
          allowHalfOpen: true,
          _transformState: {
            afterTransform: [Function: bound afterTransform],
            needTransform: true,
            transforming: true,
            writecb: [Function (anonymous)],
            writechunk: [File],
            writeencoding: 'utf8'
          },
          _destroyed: false,
          _transform: [Function: writeFile],
          [Symbol(kCapture)]: false
        },
        _readable2: DestroyableTransform {
          _readableState: ReadableState {
            objectMode: true,
            highWaterMark: 16,
            buffer: [BufferList],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: null,
            ended: false,
            endEmitted: false,
            reading: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: true,
            resumeScheduled: false,
            destroyed: false,
            defaultEncoding: 'utf8',
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null
          },
          readable: true,
          _events: [Object: null prototype] {
            end: [Array],
            prefinish: [Function: prefinish],
            close: [Array],
            finish: [Array],
            error: [Array],
            unpipe: [Function: onunpipe],
            drain: [Function (anonymous)],
            readable: [Function: onreadable]
          },
          _eventsCount: 8,
          _maxListeners: undefined,
          _writableState: WritableState {
            objectMode: true,
            highWaterMark: 16,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: false,
            decodeStrings: true,
            defaultEncoding: 'utf8',
            length: 1,
            writing: true,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function (anonymous)],
            writecb: [Function: nop],
            writelen: 1,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 1,
            prefinished: false,
            errorEmitted: false,
            bufferedRequestCount: 0,
            corkedRequestsFree: [CorkedRequest]
          },
          writable: true,
          allowHalfOpen: true,
          _transformState: {
            afterTransform: [Function: bound afterTransform],
            needTransform: true,
            transforming: true,
            writecb: [Function (anonymous)],
            writechunk: [File],
            writeencoding: 'utf8'
          },
          _destroyed: false,
          _transform: [Function: writeFile],
          [Symbol(kCapture)]: false
        },
        _autoDestroy: false,
        _forwardDestroy: false,
        _forwardEnd: true,
        _corked: 0,
        _ondrain: null,
        _drained: true,
        _forwarding: false,
        _unwrite: [Function: clear],
        _unread: [Function: clear],
        _ended: false,
        [Symbol(kCapture)]: false
      },
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [
        [Function: bound onceWrapper] { listener: [Function: onend] },
        [Function: bound onceWrapper] { listener: [Function: onend] }
      ],
      prefinish: [Function: prefinish],
      data: [Function: ondata]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 1,
      writing: true,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: [Function: nop],
      writelen: 1,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: CorkedRequest {
        next: null,
        entry: null,
        finish: [Function (anonymous)]
      }
    },
    writable: true,
    allowHalfOpen: true,
    _transformState: {
      afterTransform: [Function: bound afterTransform],
      needTransform: true,
      transforming: true,
      writecb: [Function (anonymous)],
      writechunk: File {
        stat: Stats {
          dev: 16777232,
          mode: 33188,
          nlink: 1,
          uid: 501,
          gid: 20,
          rdev: 0,
          blksize: 4096,
          ino: 10443141,
          size: 5778,
          blocks: 16,
          atimeMs: 1628853026866.1733,
          mtimeMs: 1628853018941.6216,
          ctimeMs: 1628853018941.6216,
          birthtimeMs: 1620653259584.7012,
          atime: 2021-08-13T11:10:26.866Z,
          mtime: 2021-08-13T11:10:18.942Z,
          ctime: 2021-08-13T11:10:18.942Z,
          birthtime: 2021-05-10T13:27:39.585Z
        },
        _contents: Buffer(5778) [Uint8Array] [
          123,  37,  32, 115, 101, 116,  32, 110,  97, 109, 101,  32,
           61,  32,  34,  65,  98, 111, 117, 116,  34,  32,  37, 125,
           10, 123,  37,  32, 115, 101, 116,  32, 108, 111, 103, 111,
           32,  61,  32,  34, 108, 111, 103, 105, 110,  95, 115,  99,
          114, 101, 101, 110,  34,  32,  37, 125,  10, 123,  37,  32,
          115, 101, 116,  32, 116, 105, 116, 108, 101,  32,  61,  32,
           34,  83, 116, 101, 101, 114, 105, 110, 103,  32,  67, 111,
          109, 109, 105, 116, 116, 101, 101,  34,  32,  37, 125,  10,
          123,  37,  32, 115,
          ... 5678 more items
        ],
        history: [
          '/Users/nembal/Documents/GitHub/decentralized-identity.github.io/templates/pages/governance/about.html'
        ],
        _cwd: '/Users/nembal/Documents/GitHub/decentralized-identity.github.io',
        _base: '/Users/nembal/Documents/GitHub/decentralized-identity.github.io/templates/pages',
        _isVinyl: true,
        _symlink: null
      },
      writeencoding: 'utf8'
    },
    _destroyed: false,
    _transform: [Function (anonymous)],
    [Symbol(kCapture)]: false
  },
  domainThrown: false

**Comment by csuwildcat** [comment]
Definitely something in the variables of that template's content that's malformed, so it's throwing a parse error

**Comment by nembal** [comment]
Any tips how to solve?
The case is, I tried to just copy paste an older version of the page
template when it worked, and that is also not going through gulp watch
anymore.
